expected-from-site-level-config:
  fs_default_name: { type: str(), required: true , use_default: false}
  hdfs_dfs_replication: { type: int(), required: true, use_default: true }
  yarn_app_mapreduce_am_resource_mb: { type: int(), required: true, use_default: true }
  mapreduce_map_memory_mb: { type: int(), required: true, use_default: true }
  mapreduce_reduce_memory_mb: { type: int(), required: true, use_default: true }
  yarn_resource_manager_hostname: { type: str(), required: true, use_default: false }
  yarn_nodemanager_resource_memory_mb: { type: int(), required: true, use_default: true}
  yarn_scheduler_maximum_allocation_mb: { type: int(), required: true, use_default: true}
  yarn_scheduler_minimum_allocation_mb: { type: int(), required: true, use_default: true}